window.GLOSSARY_EXTRA = [
  { unit: 1, term: "Real number", definition: "Any number that can be placed on the number line; the set of all rational and irrational numbers." },
  { unit: 1, term: "Integer", definition: "The set of whole numbers and their opposites: …, −3, −2, −1, 0, 1, 2, 3, …" },
  { unit: 1, term: "Whole number", definition: "The numbers 0, 1, 2, 3, …; non-negative integers." },
  { unit: 1, term: "Repeating decimal", definition: "A decimal in which a digit or block of digits repeats forever; every repeating decimal is rational." },
  { unit: 1, term: "Terminating decimal", definition: "A decimal that ends after a finite number of digits; a special case of a repeating decimal and therefore rational." },
  { unit: 1, term: "Decimal expansion", definition: "The decimal representation of a number, which either terminates, repeats, or continues without repeating." },
  { unit: 1, term: "Base of a power", definition: "The number being multiplied by itself; in 3⁴ the base is 3." },
  { unit: 1, term: "Exponent", definition: "The number that tells how many times the base is used as a factor; in 3⁴ the exponent is 4." },
  { unit: 1, term: "Power", definition: "An expression of the form aⁿ; also the value of that expression." },
  { unit: 1, term: "Zero exponent", definition: "For a ≠ 0, a⁰ = 1. The pattern of dividing by the base each time the exponent drops by 1 leads here." },
  { unit: 1, term: "Negative exponent", definition: "For a ≠ 0, a⁻ⁿ = 1/aⁿ. A negative exponent writes a reciprocal, not a negative value." },
  { unit: 1, term: "Product rule", definition: "aᵐ · aⁿ = aᵐ⁺ⁿ when the bases are the same. Add the exponents; do not multiply the bases." },
  { unit: 1, term: "Quotient rule", definition: "aᵐ / aⁿ = aᵐ⁻ⁿ when the bases are the same and a ≠ 0." },
  { unit: 1, term: "Power rule", definition: "(aᵐ)ⁿ = aᵐⁿ. A power of a power multiplies the exponents." },
  { unit: 1, term: "Principal square root", definition: "The non-negative square root of a number; √9 = 3, not −3, even though (−3)² is also 9." },
  { unit: 1, term: "Radical", definition: "A symbol that asks for a root; √n is a square root, ³√n is a cube root." },
  { unit: 1, term: "Standard form of a number", definition: "A number written in ordinary decimal notation, not as a × 10ⁿ. 4,500 is standard form; 4.5 × 10³ is scientific notation." },
  { unit: 1, term: "Order of magnitude", definition: "A factor-of-ten comparison. 3 × 10⁶ is two orders of magnitude larger than 3 × 10⁴." },

  { unit: 2, term: "Proportional relationship", definition: "A relationship that can be written y = kx; its graph is a straight line through the origin and the unit rate is the slope." },
  { unit: 2, term: "Unit rate", definition: "A rate with a denominator of 1; for a proportional graph it is the slope." },
  { unit: 2, term: "Constant of proportionality", definition: "The number k in y = kx; the amount y changes when x increases by 1." },
  { unit: 2, term: "Rise", definition: "The vertical change between two points on a line; y₂ − y₁." },
  { unit: 2, term: "Run", definition: "The horizontal change between two points on a line; x₂ − x₁." },
  { unit: 2, term: "Linear equation", definition: "An equation whose graph is a line. In one variable it has the form ax + b = c; in two variables, y = mx + b." },
  { unit: 2, term: "Coefficient", definition: "The number multiplied by a variable; in 7x − 3 the coefficient of x is 7." },
  { unit: 2, term: "Constant term", definition: "A term with no variable; in 7x − 3 the constant term is −3." },
  { unit: 2, term: "Like terms", definition: "Terms that have the same variable part and can be combined: 4x and −x are like terms; 4x and 4x² are not." },
  { unit: 2, term: "Distributive property", definition: "a(b + c) = ab + ac. Used to expand and, in reverse, to factor." },
  { unit: 2, term: "Variable", definition: "A letter that stands for a number that can change; in 8th grade it is usually x or y." },
  { unit: 2, term: "Solution of an equation", definition: "A number (or pair of numbers) that makes the equation true when substituted." },
  { unit: 2, term: "Equivalent equations", definition: "Equations that have the same solution set; each valid step of solving produces an equivalent equation." },
  { unit: 2, term: "Intersection point", definition: "The point where two graphs meet; for a system, the ordered pair that satisfies both equations." },
  { unit: 2, term: "Parallel lines", definition: "Lines in a plane that never meet; they have the same slope and different y-intercepts. A system of parallel lines has no solution." },
  { unit: 2, term: "Coincident lines", definition: "Two equations that graph as the same line; the system has infinitely many solutions." },
  { unit: 2, term: "Inspection", definition: "Solving a simple system by noticing a relationship — for example, x + y = 10 and x + y = 4 cannot both be true." },

  { unit: 3, term: "Relation", definition: "Any set of ordered pairs. A function is a special kind of relation." },
  { unit: 3, term: "Input", definition: "The value put into a function; an x-value; a member of the domain." },
  { unit: 3, term: "Output", definition: "The value a function produces; a y-value; a member of the range." },
  { unit: 3, term: "Mapping diagram", definition: "A picture of two ovals with arrows from inputs to outputs; used to test the one-output rule." },
  { unit: 3, term: "Function notation", definition: "f(x) names the output when the input is x. f(x) is not f times x." },
  { unit: 3, term: "Ordered pair", definition: "A pair (x, y) that records an input and its output, or a point on the coordinate plane." },
  { unit: 3, term: "Independent variable", definition: "The input variable; the quantity you choose or that time usually plays. Graphed on the horizontal axis." },
  { unit: 3, term: "Dependent variable", definition: "The output variable; its value depends on the input. Graphed on the vertical axis." },
  { unit: 3, term: "Constant rate", definition: "A rate of change that stays the same; the mark of a linear function." },
  { unit: 3, term: "Increasing interval", definition: "A stretch of a graph that goes up as you read left to right; the output grows as the input grows." },
  { unit: 3, term: "Decreasing interval", definition: "A stretch of a graph that goes down as you read left to right." },
  { unit: 3, term: "Qualitative graph", definition: "A sketch that shows the story of a situation — speeding up, stopping, turning around — without exact numbers." },
  { unit: 3, term: "Vertical line", definition: "A line with undefined slope; x = a. Used in the vertical line test." },

  { unit: 4, term: "Transformation", definition: "A rule that moves or resizes a figure: translation, reflection, rotation, or dilation." },
  { unit: 4, term: "Rigid transformation", definition: "A transformation that preserves distance and angle: translation, reflection, or rotation. Rigid transformations produce congruent images." },
  { unit: 4, term: "Preimage", definition: "The original figure before a transformation." },
  { unit: 4, term: "Image", definition: "The figure after a transformation; often named with primes: A' is the image of A." },
  { unit: 4, term: "Line of reflection", definition: "The mirror line a figure is flipped across; every point and its image are the same distance from this line." },
  { unit: 4, term: "Center of rotation", definition: "The fixed point a figure turns around; in this course often the origin." },
  { unit: 4, term: "Center of dilation", definition: "The fixed point from which a figure is enlarged or reduced; lengths are multiplied by the scale factor from this point." },
  { unit: 4, term: "Coordinate plane", definition: "The plane formed by a horizontal x-axis and a vertical y-axis crossing at the origin." },
  { unit: 4, term: "Origin", definition: "The point (0, 0) where the axes meet." },
  { unit: 4, term: "Corresponding angles", definition: "Angles in the same position at each intersection when a transversal cuts two lines; equal if the lines are parallel." },
  { unit: 4, term: "Alternate interior angles", definition: "Interior angles on opposite sides of a transversal; equal if the lines are parallel." },
  { unit: 4, term: "Same-side interior angles", definition: "Interior angles on the same side of a transversal; supplementary if the lines are parallel." },
  { unit: 4, term: "Exterior angle of a triangle", definition: "An angle formed by one side of a triangle and the extension of an adjacent side; equal to the sum of the two remote interior angles." },
  { unit: 4, term: "Triangle angle sum", definition: "The three interior angles of any triangle add to 180°." },
  { unit: 4, term: "AA similarity", definition: "If two angles of one triangle are congruent to two angles of another, the triangles are similar." },
  { unit: 4, term: "Legs of a right triangle", definition: "The two sides that form the right angle; a and b in a² + b² = c²." },
  { unit: 4, term: "Converse of the Pythagorean Theorem", definition: "If a² + b² = c² for the sides of a triangle, then the triangle is right with the right angle opposite c." },
  { unit: 4, term: "Pythagorean triple", definition: "Three positive integers a, b, c that satisfy a² + b² = c², such as 3-4-5 or 5-12-13." },
  { unit: 4, term: "Distance formula", definition: "The distance between (x₁, y₁) and (x₂, y₂) is √[(x₂ − x₁)² + (y₂ − y₁)²]; the Pythagorean Theorem on the coordinate plane." },
  { unit: 4, term: "Space diagonal", definition: "The longest segment inside a rectangular prism, from one vertex to the opposite vertex through the interior." },
  { unit: 4, term: "Volume", definition: "The amount of space a solid occupies, measured in cubic units." },
  { unit: 4, term: "Cylinder", definition: "A solid with two parallel circular bases. Volume V = πr²h." },
  { unit: 4, term: "Cone", definition: "A solid with a circular base that tapers to a point. Volume V = (1/3)πr²h — one-third the cylinder with the same base and height." },
  { unit: 4, term: "Sphere", definition: "The set of all points in space at a fixed distance r from a center. Volume V = (4/3)πr³." },
  { unit: 4, term: "Radius", definition: "A segment from the center of a circle or sphere to a point on it; also the length of that segment." },
  { unit: 4, term: "Pi", definition: "The ratio of a circle’s circumference to its diameter; an irrational number, about 3.14159, written π." },

  { unit: 5, term: "Quantitative data", definition: "Numerical measurements, such as height or hours of sleep; plotted on a scatter plot when two are paired." },
  { unit: 5, term: "Categorical data", definition: "Data that sort into labels, such as favorite subject or lunch choice; organized in a two-way table." },
  { unit: 5, term: "Cluster", definition: "A group of points on a scatter plot that sit close together, away from the rest of the data." },
  { unit: 5, term: "Linear association", definition: "A relationship whose points follow a straight-line trend, even if they do not lie exactly on a line." },
  { unit: 5, term: "Nonlinear association", definition: "A relationship whose points follow a curve or some other pattern that is not a straight line." },
  { unit: 5, term: "Strength of association", definition: "How tightly the points hug the trend: strong, moderate, or weak." },
  { unit: 5, term: "Interpolation", definition: "A prediction for an input that sits inside the range of the data; usually more trustworthy than a prediction far outside." },
  { unit: 5, term: "Extrapolation", definition: "A prediction for an input outside the range of the data; treat it with less confidence." },
  { unit: 5, term: "Confounding variable", definition: "A third variable that may be driving both of the ones you plotted; the usual reason correlation is not causation." },
  { unit: 5, term: "Spurious correlation", definition: "An association that looks strong but has no meaningful causal link — ice cream sales and drowning, for example." },
  { unit: 5, term: "Frequency", definition: "A count of how many observations fall in a category." },
  { unit: 5, term: "Marginal frequency", definition: "A row or column total in a two-way table; the count for one category ignoring the other variable." },
  { unit: 5, term: "Model", definition: "A mathematical description of a situation, such as a line of best fit; useful, and always a simplification." },
  { unit: 5, term: "Prediction", definition: "A y-value read from a model at a chosen x; it is an estimate, not a guarantee." },

  { unit: 6, term: "Cross-domain problem", definition: "A task that needs tools from two or more units — for example scientific notation and the Pythagorean Theorem in one item." },
  { unit: 6, term: "Spiral review", definition: "Returning to earlier standards on purpose so fluency does not fade while new ideas arrive." },
  { unit: 6, term: "Diagnostic", definition: "An ungraded check used to see what students already know and where reteaching should start." },
  { unit: 6, term: "Capstone", definition: "The final investigation of the year: a student-chosen question answered with at least two tools from two units." },
  { unit: 6, term: "Mathematical argument", definition: "A chain of reasons, not just an answer; what students owe a classmate who asks “why?”" },
  { unit: 6, term: "Precision", definition: "Using the right word, unit, and notation so another person can follow the work." },
  { unit: 6, term: "Persevere", definition: "Stay with a problem after the first method fails; name what was tried and try another tool." },
];
