window.LESSONS = {
  weekly: {
    note: "The daily shape stays the same. The week adds one more layer of evidence.",
    rows: [
      ["Monday–Thursday", "Full five-part lesson on the current standard"],
      ["Friday", "15-minute skills quiz (current + one spiral item), then journal or error analysis"],
      ["Day 1 of each unit", "Pre-assessment. Not graded. Used to form reteach groups."],
      ["Day 7–8 of each unit", "Checkpoint. Returned with feedback before the unit test."],
      ["Last 3–5 days", "STAR project work, peer review, presentations, then the unit test"],
    ],
  },
  template: [
    {
      name: "Header",
      text: "Standard, a student-facing objective, materials, and the one misconception you expect.",
    },
    {
      name: "Retrieve",
      text: "One problem from yesterday or a prerequisite. Circulate. Do not reteach the whole room.",
    },
    {
      name: "Launch",
      text: "A question, object, or image that makes the day’s work necessary. Keep it short.",
    },
    {
      name: "Explore",
      text: "A task students can start without you. You ask, record, and choose two pieces of work for the discussion.",
    },
    {
      name: "Discuss",
      text: "Compare methods. Name the rule only after students have something to attach it to.",
    },
    {
      name: "Check",
      text: "Three or four items on today’s standard. Sort the same day: got it, almost, not yet.",
    },
  ],
  sequences: {
    "1": [
      {
        days: "1–2",
        note: "Day 1 opens with “Can every length be measured exactly?” Students sort 20 number cards into rational/irrational and meet the nested real-number diagram. Day 2: long division produces decimal expansions; students convert repeating decimals to fractions.",
      },
      {
        days: "3",
        note: "Folded paper squares show that √2 is the diagonal of a 1×1 square. Students place √2, √3, and π on a classroom number line using benchmarks: “Is √7 closer to 2 or 3?”",
      },
      {
        days: "4–5",
        note: "Day 4 is Root War with a deck of cards and an anchor chart of 1²–15² and 1³–10³. Day 5 solves x² = p and x³ = p with area and volume contexts.",
      },
      {
        days: "6–9",
        note: "Day 6: expanded form first, rules second. Day 7: exponent foldable. Day 8: matching plus error analysis. Day 9: multi-rule problems.",
      },
      {
        days: "10–12",
        note: "Day 10: virus size, nearest star, national debt — compare them, then meet scientific notation. Day 11: convert both ways. Day 12: order values on a floor number line.",
      },
      {
        days: "13–14",
        note: "Cosmic Scale work. Students multiply and divide in scientific notation to find ratios. Day 14 is partner review of every calculation.",
      },
      {
        days: "15",
        note: "Morning: unit test on 8.NS and 8.EE.A. Afternoon: Scale Book shares. One mind-blowing fact each.",
      },
    ],
    "2": [
      {
        days: "1–2",
        note: "Day 1: paper similar triangles along one line; rise/run is constant. Day 2: two phone plans, one as a table and one as a graph — which is better?",
      },
      {
        days: "3–5",
        note: "Day 3: candle-burning tables become graphs; m and b get names. Day 4: match equation, graph, table, story. Day 5: write an equation from two points or from slope and a point.",
      },
      {
        days: "6–7",
        note: "Stations: babysitting, rentals, temperature drop. Day 7 is spoken Polygraph — one student describes a line; the partner graphs from the words only.",
      },
      {
        days: "8–10",
        note: "Balance-scale drawings, then an equation relay, then worked problems with planted mistakes.",
      },
      {
        days: "11–12",
        note: "Graph pairs: intersecting, parallel, identical. Then write one equation of each type and defend it two ways.",
      },
      {
        days: "13–16",
        note: "Graphing on large grids, substitution notes, elimination by adding related equations, then a card sort: which method, and why.",
      },
      {
        days: "17–19",
        note: "Three teacher-given break-even stories, then two days on the Business Plan: equations, hand graph, algebraic solution, report.",
      },
      {
        days: "20",
        note: "Morning test. Afternoon: three-minute investor pitches.",
      },
    ],
    "3": [
      {
        days: "1–2",
        note: "A student is the machine (secretly +3). Classmates feed index cards and guess the rule. Day 2: sort relations with the vertical line test and the one-output rule.",
      },
      {
        days: "3–4",
        note: "Four-corner representations on graph paper, then a gallery walk. Day 4 translates among equation, table, graph, and story.",
      },
      {
        days: "5–7",
        note: "Babysitting, a draining tub, a car rental — all four forms from words. Then rename slope as rate of change and b as initial value.",
      },
      {
        days: "8–9",
        note: "Partners hold different representations of two functions and must decide, without showing, which rate and which start is larger.",
      },
      {
        days: "10–11",
        note: "Toothpick growing patterns. Constant first differences vs. not. Linear vs. nonlinear from the table first, then the graph.",
      },
      {
        days: "12–14",
        note: "Teacher reads a car-trip story; students sketch in real time. Then match graphs to stories and write a story for a graph.",
      },
      {
        days: "15–17",
        note: "Function Machine Game Show: four functions, four representations, live host segment.",
      },
      { days: "18", note: "Unit test on 8.F." },
    ],
    "4": [
      {
        days: "1–3",
        note: "Patty paper slides give (x+a, y+b). Folds give reflections across the axes and y = x. Then practice on a coordinate grid.",
      },
      {
        days: "4–5",
        note: "Pencil at the origin, rotate the tracing paper. Students write the 90°, 180°, and 270° rules before they are told them.",
      },
      {
        days: "6–7",
        note: "Measure similar figures; the ratio is the scale factor. Then dilate from the origin with (kx, ky).",
      },
      {
        days: "8–10",
        note: "Sort sequences into rigid vs. not. Then two days on the Transformation Art Gallery.",
      },
      {
        days: "11–12",
        note: "Angle hunt in photos of bridges and tracks. Then a protractor station on parallel lines cut by a transversal.",
      },
      {
        days: "13–14",
        note: "Tear the corners off a paper triangle; they make a straight line. Then exterior angle and AA similarity.",
      },
      {
        days: "15–16",
        note: "Cut squares of area a², b², and c² and rearrange them. Then collect Pythagorean triples.",
      },
      {
        days: "17–19",
        note: "Dream Bedroom briefs and scale plans. Stations: ladders, space diagonals, construction. Finish the portfolio calculations.",
      },
      {
        days: "20",
        note: "Draw the right triangle between two points. The distance formula is the Pythagorean Theorem with coordinates.",
      },
      {
        days: "21",
        note: "Design a can with a fixed volume. Compare a cylinder and a cone with the same base and height. Paper models.",
      },
      {
        days: "22",
        note: "Morning test. Afternoon: bedroom portfolios. Art Gallery stays in the hall.",
      },
    ],
    "5": [
      {
        days: "1–2",
        note: "Measure height and arm span. Plot the class. Name the pattern. Day 2: strong/weak, positive/negative/none, linear/nonlinear.",
      },
      {
        days: "3–4",
        note: "Sort printed scatter plots by type and strength. Then hunt outliers in real sports or weather sheets — error or unusual case?",
      },
      {
        days: "5–7",
        note: "Uncooked spaghetti on a hand-drawn plot. Trace, pick two points, write the equation. Compare rival lines. Predict.",
      },
      {
        days: "8–9",
        note: "Write one English sentence for slope and one for intercept. Then predict, and say how far the x-value sits from the data.",
      },
      {
        days: "10",
        note: "Gallery of spurious correlations. Students say what is associated and what is not caused. What would establish cause?",
      },
      {
        days: "11–12",
        note: "Class survey into a two-way table. Then relative frequencies and a second categorical story.",
      },
      {
        days: "13",
        note: "Fifteen points, a hand plot, a spaghetti line, an equation, a correlation-is-not-causation paragraph. Peer check.",
      },
      { days: "14", note: "Morning test. Afternoon: pair presentations, one question each." },
    ],
    "6": [
      {
        days: "1",
        note: "A short year-in-review quiz. Compare it to the Unit 1 pre-assessment. Write: what do I know now that I did not know in September?",
      },
      {
        days: "2–4",
        note: "Stations by domain. Day 4 includes a teacher-led reteach group pulled from the diagnostic.",
      },
      {
        days: "5–6",
        note: "Three cross-domain problems. Name the units first. Day 6 is a seminar: which tool, and would another have worked?",
      },
      {
        days: "7",
        note: "Students find their own work that shows each mathematical practice. Revisit the math biography. One peer appreciation each.",
      },
      {
        days: "8–11",
        note: "Capstone: question, five-minute conferences, structured peer feedback, then a 3–4 minute showcase. Families invited.",
      },
    ],
  },
  models: [
    {
      id: "u1-d1",
      unit: 1,
      days: "1",
      title: "Can every length be measured exactly?",
      standards: ["8.NS.A.1"],
      objective: "Classify a number as rational or irrational and give a reason that uses the decimal or the fraction definition.",
      materials: ["20 number cards (mix of fractions, terminating decimals, repeating decimals, π, √2, √5, 0.121221222…)", "class chart with two columns", "nested real-number diagram"],
      retrieve: "Write 3/8 and 1/3 as decimals. What is the same? What is different?",
      launch: "Hold up a ruler. Ask: can every length on this ruler be written as a fraction of an inch? Take two answers and do not settle the argument.",
      explore: "Pairs sort the 20 cards onto the class chart. They must write one justification per card: fraction, terminates, repeats, or never repeats. Circulate for the cards that look rational and are not — especially 0.121221222… and √9.",
      discuss: "Put three disputed cards under the document camera. Name the nested diagram only after the sort: integers inside rationals inside reals. Irrationals are the leftovers that still have a place on the line.",
      check: "1) Is 0.6̅ rational? Why? 2) Is √16 rational? Why? 3) Place √2 on the diagram and write one sentence. 4) Write a number that is real but not rational.",
      misconception: "Students treat “looks messy” as irrational, so they call 2/7 or 0.1212… irrational. Require the test: can it be written p/q, or does the decimal eventually repeat?",
      support: "Give a reference card: terminates or repeats → rational. Offer the nested diagram already labeled.",
      extend: "Ask for a proof-sketch that a repeating decimal can always be written as a fraction, using 0.3̅ as the model.",
    },
    {
      id: "u1-d3",
      unit: 1,
      days: "3",
      title: "Where does √2 live?",
      standards: ["8.NS.A.2", "8.EE.A.2"],
      objective: "Approximate an irrational square root to the nearest tenth and place it on a number line using perfect-square benchmarks.",
      materials: ["1×1 paper squares", "scissors", "classroom number line from 0 to 4", "calculators only for the last check"],
      retrieve: "Name the two perfect squares on either side of 7. What does that tell you about √7?",
      launch: "Fold a 1×1 square along the diagonal. How long is that cut? Students will say “a little more than 1.” Write √2 and leave it.",
      explore: "Each pair locates √2, √3, √5, √8, and π on the wall number line. They must write the two integers it sits between and decide which tenth is closer without a calculator first. Then they check one value on a calculator and revise if needed.",
      discuss: "Compare two placements of √8. One pair used 2 and 3; another noticed √8 = 2√2. Both are legal. The point is the method: sandwich with perfect squares, then refine.",
      check: "Place √11 on a 0–4 line and explain the tenths. Which is larger, √10 or 3.1? Estimate π² to the nearest whole number.",
      misconception: "Students think √n is “n divided by 2,” or they put √2 at 2. Keep the square visible so the length is a side, not an area.",
      support: "A two-column chart: perfect squares 1–16 in one column, roots in the other. Number line already marked in tenths.",
      extend: "Locate −√2 and √2 + 1. Ask how a rational plus an irrational must come out.",
    },
    {
      id: "u1-d6",
      unit: 1,
      days: "6",
      title: "The rules come last",
      standards: ["8.EE.A.1"],
      objective: "Generate the product, quotient, and power rules from expanded form, then use them to write an equivalent expression.",
      materials: ["expanded-form cards (2³ · 2⁴, 5⁶ / 5², (3²)⁴)", "blank foldable for tomorrow"],
      retrieve: "Write 2⁴ as a product. Write 2¹ and 2⁰ as a guess — we will come back to the zero.",
      launch: "Put 2³ · 2⁴ on the board. Do not say the rule. “Write it without exponents, then write it with one exponent.”",
      explore: "Three stations, ten minutes each: product, quotient, power of a power. At each station students expand, count, and write a sentence that starts “I notice…”. They do not copy a boxed rule until the discussion.",
      discuss: "Collect the three sentences. Only then write a^m · a^n = a^{m+n} and the other two. Ask a pair to try 3⁰ from the pattern, not from a definition.",
      check: "Simplify 5² · 5³, 7⁶ / 7², (2³)², and 4⁰. One error-analysis item: a student wrote 2³ · 2⁴ = 4⁷.",
      misconception: "Bases get multiplied when exponents are added, or exponents are multiplied for a product. Keep the expanded form on the wall for a week.",
      support: "Same bases only today. A three-row table: expanded, counted, compact.",
      extend: "What happens if the bases are different? Why is 2³ · 3³ not 6³ — or is it? Have them expand.",
    },
    {
      id: "u2-d1",
      unit: 2,
      days: "1",
      title: "The ratio that does not change",
      standards: ["8.EE.B.5", "8.EE.B.6"],
      objective: "Measure rise and run on similar triangles along one line and explain why the slope is the same between any two points.",
      materials: ["one large graphed line on chart paper per group", "three paper right triangles of different sizes", "rulers"],
      retrieve: "A phone plan costs $15 per gigabyte with no fee. Make a table for 0, 1, 2, 3 GB. Where does the graph start?",
      launch: "Lay the three triangles against the same line. “These triangles are different sizes. What might still be the same?”",
      explore: "Groups measure rise and run for each triangle and compute rise ÷ run. They then pick two new points on the line, draw their own triangle, and compute again. Every ratio should be close to the same number.",
      discuss: "Put two groups’ tables side by side. Name that number slope, and name it unit rate when the graph goes through the origin. Sketch why the triangles are similar — corresponding angles with a transversal.",
      check: "Find the slope between (1, 3) and (4, 9). A second graph through the origin: which has the greater unit rate? Write one sentence.",
      misconception: "Students compute run ÷ rise, or they think a steeper line “has more numbers.” Have them walk the line with a finger: up, then over.",
      support: "Color rise one color and run another. A slope card that already says rise / run.",
      extend: "Why does a line that does not go through the origin still have a constant slope? Tomorrow’s candle data will need that.",
    },
    {
      id: "u2-d11",
      unit: 2,
      days: "11",
      title: "One, none, or all of them",
      standards: ["8.EE.C.7a"],
      objective: "Decide whether a linear equation has one solution, no solution, or infinitely many, and show it both by graphing and by simplifying.",
      materials: ["large grids", "three prepared equation pairs: intersecting, parallel, identical"],
      retrieve: "Solve 2x + 1 = 7. How many numbers work? How do you know you are done?",
      launch: "Graph y = 2x + 1 and y = 2x − 4 on the same grid without talking. “What do you notice? What do you wonder?”",
      explore: "Three stations, one pair of equations each. At every station: graph both, simplify the corresponding one-variable equation, and write a verdict. Students rotate so every group sees all three types.",
      discuss: "Build the dictionary together: intersecting → one solution → x = a number. Parallel → no solution → 0 = 5. Same line → infinitely many → 0 = 0. Students must say the graph and the algebra in the same breath.",
      check: "Classify 3x − 2 = 3x + 4, 2(x + 1) = 2x + 2, and 5x + 1 = 2x − 8. Create one new equation of each type.",
      misconception: "“No solution” is treated as x = 0, and “infinite” as “I got stuck.” Force the last line of the algebra onto the page: 0 = 5 or 0 = 0.",
      support: "A three-column flowchart: last line is x = __, 0 = nonzero, 0 = 0.",
      extend: "Write a system of two lines that is the same story as “no solution.” Tomorrow’s systems work starts here.",
    },
    {
      id: "u3-d1",
      unit: 3,
      days: "1",
      title: "The human function machine",
      standards: ["8.F.A.1"],
      objective: "State the definition of a function and decide whether a relation is a function from a mapping, a table, or a graph.",
      materials: ["index cards", "a volunteer “machine”", "mapping-diagram posters"],
      retrieve: "A vending machine: you press B4. Can two different snacks fall out? Why does that matter?",
      launch: "One student is the machine and secretly adds 3. Classmates send inputs on cards and record outputs. After eight cards, they guess the rule. Then send the same input twice — the output must match.",
      explore: "Card sort: mappings, tables, and graphs. Function or not? Each card needs one sentence that uses “input,” “output,” or “vertical line.” Include a circle that fails the vertical line test and a table with a repeated x and two y-values.",
      discuss: "Write the definition only after the sort. Function notation f(x) is a name for the machine, not a multiplication. Evaluate f(4) for the +3 machine.",
      check: "Is {(1, 2), (1, 5), (3, 4)} a function? Sketch a graph that fails the vertical line test. Given f(x) = 2x − 1, find f(0) and f(5).",
      misconception: "Students think “function” means “linear,” or that a repeated y-value breaks the rule. Repeat: the danger is one x with two y-values.",
      support: "A physical in-box and out-box. Sentence frame: “This is not a function because the input __ maps to __ and __.”",
      extend: "A piecewise story: a ride-share that charges one rate, then another. Is it still a function? Why?",
    },
    {
      id: "u4-d15",
      unit: 4,
      days: "15",
      title: "Squares that rearrange",
      standards: ["8.G.B.6", "8.G.B.7"],
      objective: "Explain a visual proof of the Pythagorean Theorem and use a² + b² = c² to find a missing side.",
      materials: ["paper squares of area 9, 16, and 25", "a 3-4-5 right triangle", "scissors", "one other triple for each pair"],
      retrieve: "A right triangle has legs 6 and 8. Before any formula, sketch the three squares on the sides and guess which two add to the third.",
      launch: "Silent demonstration: place the 9 and 16 squares, then cut and rearrange them onto the 25. Do not say the theorem yet. “What just happened?”",
      explore: "Pairs cut their own a² and b² and try the rearrangement on c². Then they test a non-right triangle — the squares will not fit. Last, they find the missing side of a 5-12-? triangle by the same idea, not by a memorized list.",
      discuss: "Write a² + b² = c² and name the hypotenuse. Show one more proof image (the rearrangement the class used). Students say the converse in their own words: if the squares add, the angle is right. That sentence will do work in the bedroom project.",
      check: "Legs 9 and 12, find the hypotenuse. Hypotenuse 15, one leg 9, find the other. A triangle with sides 6, 8, 11 — right or not?",
      misconception: "Students add the legs, or they put the hypotenuse in for a. Keep the squares on the desk so c is visibly the longest side.",
      support: "A labeled 3-4-5 with the three squares already drawn. Triple list: 3-4-5, 5-12-13, 8-15-17, as a check, not a first method.",
      extend: "The space diagonal of a 3 × 4 × 12 room. Tomorrow’s 3D stations start with that question.",
    },
    {
      id: "u5-d5",
      unit: 5,
      days: "5",
      title: "The spaghetti line",
      standards: ["8.SP.A.2", "8.SP.A.3"],
      objective: "Informally fit a line to a scatter plot, write its equation from two points on the line, and judge whether the fit is reasonable.",
      materials: ["class height-vs-arm-span plot from Day 1, enlarged", "uncooked spaghetti", "rulers"],
      retrieve: "Look at the class scatter plot. Point to a cluster. Point to an outlier. Is the association positive?",
      launch: "Hold up one piece of spaghetti. “This is the only line you get. Where will you lay it, and what would a bad placement look like?”",
      explore: "Each pair lays spaghetti, traces, picks two convenient points on the line (not necessarily data points), and writes y = mx + b. They then measure, roughly, how many points sit far from the line. Switch plots with another pair and critique the fit in one sentence.",
      discuss: "Project two rival lines. Neither is “the” line. The better one has a slope that matches the cloud and does not chase a single outlier. Interpret m in context: additional centimeters of height, additional centimeters of arm span.",
      check: "A five-point plot is on the half-sheet. Draw a line, write the equation, and predict y when x = 10. Say whether that prediction is interpolation or a stretch.",
      misconception: "Students force the line through the origin, or through the first and last data points, or through an outlier. The line is a model of the trend, not a connect-the-dots.",
      support: "A plotted example with the line already drawn; students only write the equation. Sentence frame for slope in context.",
      extend: "Tomorrow they will compare two lines on the same plot and argue. Advanced pairs can try Desmos regression after the hand line exists.",
    },
    {
      id: "u5-d10",
      unit: 5,
      days: "10",
      title: "Associated is not caused",
      standards: ["8.SP.A.1", "8.SP.A.3"],
      objective: "Distinguish correlation from causation and name a possible confounding variable in a real association.",
      materials: ["8–10 printed spurious-correlation posters (ice cream and drowning, and similar)", "sticky notes"],
      retrieve: "The class line of best fit for hours of sleep vs. quiz score had a positive slope. Write one sentence that is safe, and one sentence that claims too much.",
      launch: "First poster, no title. “What do you see? What do you think is going on?”",
      explore: "Gallery walk. At each poster students write: the two variables, the direction of association, and one other variable that could be driving both. No phones. The point is the argument, not the meme.",
      discuss: "Collect confounders: weather, age, time of year, wealth. Write the two definitions. Causation needs a design that isolates a cause — a random assignment, a controlled experiment — not a tidy scatter plot. The Data Detectives report will require this paragraph.",
      check: "A serious pair: number of firefighters vs. damage at a fire. Association? Cause? Confounder? Then: shoe size vs. reading score in K–8. Same three questions.",
      misconception: "Students think “we found a line, so one variable makes the other happen.” Keep the firefighter example; it is harder to laugh off than Nicolas Cage.",
      support: "Sentence frames: “As __ increases, __ tends to __. This does not mean __. A third variable could be __.”",
      extend: "What evidence would you demand from a medical study before you believed a cause? Bring that bar to the project.",
    },
    {
      id: "u6-d5",
      unit: 6,
      days: "5",
      title: "Name the tools first",
      standards: ["8.EE.C.8c", "8.G.B.7", "8.SP.A.3", "8.F.B.4"],
      objective: "On a problem that mixes two domains, name the units involved, choose a tool, and solve with the work visible.",
      materials: ["three cross-domain problems from Unit 6", "unit-tool posters (one per domain)"],
      retrieve: "List one tool from each of Units 1–5 in thirty seconds. This is a memory dump, not a quiz.",
      launch: "Put the ladder problem on the board. “Before anyone computes: which units are in the room?” Wait until someone says geometry and functions.",
      explore: "Groups get all three problems. First move, required: write the unit numbers and the tool they will try. Then they solve one problem fully and sketch a path for the other two. You conference, you do not lecture.",
      discuss: "One group presents the ladder: table of base vs. height, then the claim that the change is nonlinear. Another presents the study-hours line. Ask: would a system have worked on the functions problem? The seminar is about choice, not speed.",
      check: "A fourth short mix: a 5 × 12 right triangle with sides written in scientific notation. Find the hypotenuse and write it as a × 10^n.",
      misconception: "Students grab the most recent unit and ignore the diagram. The first written line of every solution is the tool list. Grade that line.",
      support: "A one-page toolkit: one example and one formula per unit. They may use it today.",
      extend: "Write a fifth cross-domain problem that uses statistics and geometry. Swap with another group tomorrow.",
    },
  ],
};
